/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as SavoirFaireRouteImport } from './routes/savoir-faire'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminJkRouteImport } from './routes/admin-jk'
import { Route as IndexRouteImport } from './routes/index'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const SavoirFaireRoute = SavoirFaireRouteImport.update({
  id: '/savoir-faire',
  path: '/savoir-faire',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJkRoute = AdminJkRouteImport.update({
  id: '/admin-jk',
  path: '/admin-jk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-jk': typeof AdminJkRoute
  '/contact': typeof ContactRoute
  '/offres': typeof OffresRoute
  '/realisations': typeof RealisationsRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/temoignages': typeof TemoignagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-jk': typeof AdminJkRoute
  '/contact': typeof ContactRoute
  '/offres': typeof OffresRoute
  '/realisations': typeof RealisationsRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/temoignages': typeof TemoignagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-jk': typeof AdminJkRoute
  '/contact': typeof ContactRoute
  '/offres': typeof OffresRoute
  '/realisations': typeof RealisationsRoute
  '/savoir-faire': typeof SavoirFaireRoute
  '/temoignages': typeof TemoignagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-jk'
    | '/contact'
    | '/offres'
    | '/realisations'
    | '/savoir-faire'
    | '/temoignages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-jk'
    | '/contact'
    | '/offres'
    | '/realisations'
    | '/savoir-faire'
    | '/temoignages'
  id:
    | '__root__'
    | '/'
    | '/admin-jk'
    | '/contact'
    | '/offres'
    | '/realisations'
    | '/savoir-faire'
    | '/temoignages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminJkRoute: typeof AdminJkRoute
  ContactRoute: typeof ContactRoute
  OffresRoute: typeof OffresRoute
  RealisationsRoute: typeof RealisationsRoute
  SavoirFaireRoute: typeof SavoirFaireRoute
  TemoignagesRoute: typeof TemoignagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savoir-faire': {
      id: '/savoir-faire'
      path: '/savoir-faire'
      fullPath: '/savoir-faire'
      preLoaderRoute: typeof SavoirFaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-jk': {
      id: '/admin-jk'
      path: '/admin-jk'
      fullPath: '/admin-jk'
      preLoaderRoute: typeof AdminJkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminJkRoute: AdminJkRoute,
  ContactRoute: ContactRoute,
  OffresRoute: OffresRoute,
  RealisationsRoute: RealisationsRoute,
  SavoirFaireRoute: SavoirFaireRoute,
  TemoignagesRoute: TemoignagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
